cache: bundler
sudo: false

before_install:
  - gem install bundler

rvm:
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-9000
  - rbx-3

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
    - rvm: jruby-9000

script:
  - "bundle exec rake"

addons:
  code_climate:
    repo_token: b84ce34b20f2a809814493585d027aa71ab07e13116bf68430511548815d9411

notifications:
  email:
    recipients:
      - benny.klotz92@gmail.com
    email:
      on_failure: change
      on_success: change
