cache: bundler
sudo: false

before_install:
  - gem install bundler

rvm:
  - 2.5.*
  - 2.6.*
  - 2.7.*
  - ruby-head
  - jruby-9.2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2

script:
  - CODECLIMATE_REPO_TOKEN=b84ce34b20f2a809814493585d027aa71ab07e13116bf68430511548815d9411 bundle exec rake

addons:
  code_climate:
    repo_token: b84ce34b20f2a809814493585d027aa71ab07e13116bf68430511548815d9411

notifications:
  email:
    recipients:
      - benny.klotz92@gmail.com
    email:
      on_failure: change
      on_success: change
